@startuml
class Classifier {
~ Context context
- {static} String MODEL_NAME
~ Interpreter interpreter
~ int modelInputWidth
~ int modelInputHeight
~ int modelInputChannel
- ByteBuffer loadModelFile(String)
+ void init()
- void initModelShape()
- Bitmap resizeBitmap(Bitmap)
- ByteBuffer convertBitmapToGrayByteBuffer(Bitmap)
+ float classify(Bitmap)
+ void finish()
}
class MainActivity {
- TextView textView
~ Classifier cls
~ View.OnTouchListener listener
# void onCreate(Bundle)
# void onDestroy()
}


AppCompatActivity <|-- MainActivity
@enduml